import React, { useState } from 'react';
import { navigationTabs } from '../data/navigation';

export function Header() {
  const [activeTab, setActiveTab] = useState('homes');

  return (
    <header className="[align-items:normal] box-content block h-auto justify-normal max-w-none mx-0 px-0 md:items-center md:aspect-auto md:box-border md:flex md:h-20 md:justify-between md:max-w-[1920px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mx-auto md:px-8 md:scroll-m-0 md:scroll-p-[auto]">
      <a aria-label="Airbnb homepage" href="/" className="static text-black [align-items:normal] box-content inline h-auto min-h-0 min-w-0 align-baseline z-auto md:relative md:text-rose-500 md:items-center md:aspect-auto md:box-border md:flex md:h-20 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] before:md:accent-auto before:md:box-border before:md:text-rose-500 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-normal before:md:tracking-[normal] before:md:leading-[20.02px] before:md:list-outside before:md:list-disc before:md:absolute before:md:text-start before:md:indent-[0px] before:md:normal-case before:md:visible before:md:rounded-xl before:md:border-separate before:md:-inset-x-3 before:md:inset-y-3 before:md:font-airbnb_cereal_vf">
        <div className="box-content min-h-0 min-w-0 md:aspect-auto md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <img src="https://c.animaapp.com/me7emf7wZc0xCu/assets/icon-2.svg" alt="Icon" className="box-content h-auto align-middle w-auto md:aspect-auto md:box-border md:h-8 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-[102px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
        </div>
        <div className="box-content block md:aspect-auto md:box-border md:hidden md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <img src="https://c.animaapp.com/me7emf7wZc0xCu/assets/icon-3.svg" alt="Icon" className="box-content h-auto align-middle w-auto md:aspect-auto md:box-border md:h-8 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-[30px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
        </div>
      </a>
      
      <form role="search" className="static box-content h-auto w-auto z-auto px-0 left-auto top-auto md:absolute md:aspect-auto md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-0 md:[mask-position:0%] md:bg-left-top md:px-8 md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-0">
        <div className="static [align-items:normal] box-content block flex-row w-auto z-auto md:relative md:items-center md:aspect-auto md:box-border md:flex md:flex-col md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="box-content min-h-0 min-w-0 md:aspect-auto md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <div className="box-content w-auto m-0 md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[500px] md:[mask-position:0%] md:bg-left-top md:mt-[22px] md:mb-6 md:mx-auto md:scroll-m-0 md:scroll-p-[auto]">
              <div role="tablist" className="static box-content gap-x-[normal] block grid-cols-none justify-normal gap-y-[normal] mt-0 md:relative md:aspect-auto md:box-border md:gap-x-[35px] md:grid md:grid-cols-[repeat(3,min-content)] md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:gap-y-[35px] md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-2 md:scroll-m-0 md:scroll-p-[auto]">
                {navigationTabs.map((tab) => (
                  <a 
                    key={tab.id}
                    href={tab.href} 
                    role="tab" 
                    className={tab.id === 'homes' ? "[align-items:normal] box-content inline min-h-0 min-w-0 ml-0 mb-0 pl-0 md:items-center md:aspect-auto md:box-border md:flex md:ml-[-5px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mb-3 md:pl-[5px] md:scroll-m-0 md:scroll-p-[auto]" : tab.id === 'experiences' ? "[align-items:normal] box-content inline min-h-0 min-w-0 mb-0 md:items-center md:aspect-auto md:box-border md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mb-3 md:scroll-m-0 md:scroll-p-[auto]" : "[align-items:normal] box-content inline min-h-0 min-w-0 ml-0 mb-0 pl-0 md:items-center md:aspect-auto md:box-border md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:-ml-0.5 md:mb-3 md:pl-0.5 md:scroll-m-0 md:scroll-p-[auto]"}
                    onClick={() => setActiveTab(tab.id)}
                  >
                    <span className="static box-content inline min-h-0 min-w-0 md:relative md:aspect-auto md:box-border md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <span className="box-content inline h-auto w-auto md:aspect-auto md:box-border md:block md:h-9 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-9 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <video className="static box-content h-auto transform-none align-middle w-auto left-auto top-auto md:absolute md:aspect-auto md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:scale-[2px] md:left-0 md:top-0"></video>
                        <video className="static box-content h-auto opacity-100 transform-none align-middle w-auto left-auto top-auto md:absolute md:aspect-auto md:box-border md:h-full md:opacity-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:scale-[2px] md:left-0 md:top-0"></video>
                      </span>
                      {tab.badge && (
                        <span className="static text-base bg-none shadow-none box-content inline leading-[normal] origin-[50%_50%] p-0 rounded-none left-auto top-auto md:absolute md:text-[8px] md:aspect-auto md:bg-[linear-gradient(357.5deg,rgb(62,86,124)_1.59%,rgb(58,84,117)_21.23%,rgb(45,60,91)_58.6%,rgb(128,157,192)_97.4%)] md:shadow-[rgba(60,77,107,0.25)_0px_0.953955px_1.90791px_0px,rgba(60,77,107,0.25)_0px_3.81582px_5.72373px_0px,rgb(0,28,64)_0px_0px_2px_0.5px_inset,rgb(215,235,255)_0px_-1px_3px_0px_inset] md:box-border md:block md:leading-[11.44px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:origin-[0%_100%] md:[mask-position:0%] md:bg-left-top md:px-1.5 md:py-[3px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-bl-sm md:rounded-r-[10px] md:rounded-tl-[10px] md:left-full md:-top-2.5">
                          <span className="static text-black font-normal bg-clip-border bg-none box-content tracking-[normal] leading-[normal] text-start normal-case text-wrap md:relative md:text-white md:font-bold md:aspect-auto md:bg-clip-text md:bg-[linear-gradient(173.86deg,rgba(255,255,255,0.9)_90.56%,rgba(191,205,213,0.9)_82.32%)] md:box-border md:tracking-[0.32px] md:leading-[10px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-center md:decoration-auto md:uppercase md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            {tab.badge}
                            <span className="static text-black bg-clip-border bg-none box-content inline mix-blend-normal opacity-100 text-wrap transform-none left-auto md:absolute md:text-transparent md:aspect-auto md:bg-clip-text md:bg-[linear-gradient(to_top,rgb(255,255,255),rgba(0,0,0,0)_50%)] md:box-border md:block md:blur-[0.131901px] md:mix-blend-screen md:opacity-30 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:translate-y-[66.0%] md:scale-y-[-1px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0">{tab.badge}</span>
                            <span className="static bg-none box-content inline h-auto mix-blend-normal opacity-100 text-wrap w-auto left-auto top-auto md:absolute md:aspect-auto md:bg-[radial-gradient(50%_50%,rgb(255,248,223)_0%,rgba(255,254,224,0.2)_51.5%,rgba(255,250,225,0)_100%)] md:box-border md:block md:blur-[0.659506px] md:h-1.5 md:mix-blend-plus-lighter md:opacity-40 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-1.5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-[3px] md:top-0"></span>
                            <span className="static bg-none box-content inline h-auto mix-blend-normal opacity-100 text-wrap w-auto left-auto top-auto md:absolute md:aspect-auto md:bg-[radial-gradient(50%_50%,rgb(255,248,223)_0%,rgba(255,254,224,0.2)_51.5%,rgba(255,250,225,0)_100%)] md:box-border md:block md:blur-[0.659506px] md:h-1.5 md:mix-blend-plus-lighter md:opacity-40 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-1.5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-[14.5px] md:top-[3.5px]"></span>
                          </span>
                        </span>
                      )}
                    </span>
                    <span className={tab.id === 'homes' ? "font-normal box-content inline leading-[normal] min-h-0 min-w-0 text-wrap ml-0 md:font-semibold md:aspect-auto md:box-border md:block md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:ml-4 md:scroll-m-0 md:scroll-p-[auto] before:md:accent-auto before:md:box-border before:md:text-neutral-800 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-semibold before:md:h-0 before:md:tracking-[normal] before:md:leading-[18px] before:md:list-outside before:md:list-disc before:md:text-start before:md:indent-[0px] before:md:normal-case before:md:text-nowrap before:md:invisible before:md:overflow-hidden before:md:border-separate before:md:font-airbnb_cereal_vf" : tab.id === 'experiences' ? "text-black box-content inline leading-[normal] min-h-0 min-w-0 text-wrap ml-0 md:text-neutral-500 md:aspect-auto md:box-border md:block md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:ml-2 md:scroll-m-0 md:scroll-p-[auto] before:md:accent-auto before:md:box-border before:md:text-neutral-500 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-semibold before:md:h-0 before:md:tracking-[normal] before:md:leading-[18px] before:md:list-outside before:md:list-disc before:md:text-start before:md:indent-[0px] before:md:normal-case before:md:text-nowrap before:md:invisible before:md:overflow-hidden before:md:border-separate before:md:font-airbnb_cereal_vf" : "text-black box-content inline leading-[normal] min-h-0 min-w-0 text-wrap ml-0 md:text-neutral-500 md:aspect-auto md:box-border md:block md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:ml-3 md:scroll-m-0 md:scroll-p-[auto] before:md:accent-auto before:md:box-border before:md:text-neutral-500 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-semibold before:md:h-0 before:md:tracking-[normal] before:md:leading-[18px] before:md:list-outside before:md:list-disc before:md:text-start before:md:indent-[0px] before:md:normal-case before:md:text-nowrap before:md:invisible before:md:overflow-hidden before:md:border-separate before:md:font-airbnb_cereal_vf"}>
                      {tab.label}
                    </span>
                    <span className="static box-content inline h-auto text-wrap w-auto md:absolute md:aspect-auto md:box-border md:block md:h-px md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-px md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">{tab.ariaLabel}</span>
                  </a>
                ))}
                <div className="static box-content h-auto w-auto top-auto md:absolute md:aspect-auto md:box-border md:h-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6/12 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:top-0"></div>
                <span className="static box-content inline left-auto bottom-auto md:absolute md:aspect-auto md:box-border md:block md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:bottom-0">
                  <span className="static bg-transparent box-content inline h-auto origin-[50%_50%] w-auto rounded-l-none left-auto bottom-auto md:absolute md:aspect-auto md:bg-neutral-800 md:box-border md:block md:h-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:origin-[0%_50%] md:w-[3px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-l-[1.5px] md:left-0 md:bottom-0"></span>
                  <span className="static bg-transparent box-content inline h-auto transform-none origin-[50%_50%] w-auto left-auto bottom-auto md:absolute md:aspect-auto md:bg-neutral-800 md:box-border md:block md:h-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[3px] md:scale-x-[-0.6px] md:origin-[0%_50%] md:w-2.5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:bottom-0"></span>
                  <span className="static bg-transparent box-content inline h-auto transform-none origin-[50%_50%] w-auto rounded-r-none left-auto bottom-auto md:absolute md:aspect-auto md:bg-neutral-800 md:box-border md:block md:h-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[-3px] md:origin-[0%_50%] md:w-[3px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-r-[1.5px] md:left-0 md:bottom-0"></span>
                </span>
              </div>
            </div>
            
            <div className="static [align-items:normal] box-content gap-x-[normal] block h-auto justify-normal max-w-none gap-y-[normal] transform-none w-auto rounded-none left-auto md:absolute md:items-center md:aspect-auto md:box-border md:gap-x-3 md:flex md:h-[66px] md:justify-between md:max-w-[850px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[-50.0%] md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[32px] md:left-2/4">
              <div className="static bg-transparent box-content h-auto w-auto z-auto rounded-none left-auto top-auto md:absolute md:aspect-auto md:bg-white md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-[-3] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[100px] md:left-0 md:top-0"></div>
              <div className="[align-items:normal] box-content gap-x-[normal] block grid-cols-none h-auto min-h-0 min-w-0 gap-y-[normal] w-auto rounded-none md:items-center md:aspect-auto md:box-border md:gap-x-0.5 md:grid md:grid-cols-[minmax(0px,2fr)_1px_minmax(0px,1fr)_1px_minmax(0px,1fr)_1px_minmax(0px,2fr)] md:h-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-0.5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[32px]">
                <div className="static [align-items:normal] box-content block h-auto justify-normal min-h-0 min-w-0 w-auto rounded-none md:relative md:items-center md:aspect-auto md:box-border md:flex md:h-full md:justify-between md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[32px] before:md:accent-auto before:md:box-border before:md:text-neutral-800 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-normal before:md:h-8 before:md:tracking-[normal] before:md:leading-[20.02px] before:md:list-outside before:md:list-disc before:md:absolute before:md:text-start before:md:indent-[0px] before:md:normal-case before:md:-translate-y-4 before:md:visible before:md:w-[calc(100%_+_8px)] before:md:z-[-1] before:md:border-separate before:md:-left-1 before:md:top-2/4 before:md:font-airbnb_cereal_vf after:md:accent-auto after:md:box-border after:md:text-neutral-800 after:md:block after:md:text-sm after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[20.02px] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-[calc(100%_+_70px)] after:md:z-[-1] after:md:rounded-[32px] after:md:border-separate after:md:top-0 after:md:font-airbnb_cereal_vf">
                  <div className="static box-content min-h-0 w-auto z-auto p-0 md:relative md:aspect-auto md:box-border md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-[2] md:overflow-clip md:[mask-position:0%] md:bg-left-top md:px-8 md:py-[15px] md:scroll-m-0 md:scroll-p-[auto]">
                    <div className="text-base font-normal box-content leading-[normal] text-clip text-wrap pb-0 md:text-xs md:font-medium md:aspect-auto md:box-border md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-clip md:[mask-position:0%] md:bg-left-top md:pb-0.5 md:scroll-m-0 md:scroll-p-[auto]">Where</div>
                    <div className="box-content md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <input 
                        type="search" 
                        placeholder="Search destinations" 
                        aria-label="Where" 
                        name="query" 
                        defaultValue="" 
                        className="bg-white box-content inline-block leading-[normal] text-clip text-wrap w-auto md:aspect-auto md:bg-transparent md:box-border md:block md:leading-[18px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:w-full md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto]" 
                      />
                    </div>
                  </div>
                </div>
                <div className="bg-transparent box-content h-auto min-h-0 min-w-0 w-auto z-auto md:aspect-auto md:bg-zinc-300 md:box-border md:h-8 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-px md:z-[-2] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
                <div role="button" className="static [align-items:normal] box-content block h-auto justify-normal min-h-0 min-w-0 w-auto rounded-none md:relative md:items-center md:aspect-auto md:box-border md:flex md:h-full md:justify-between md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[32px] before:md:accent-auto before:md:box-border before:md:text-neutral-800 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-normal before:md:h-8 before:md:tracking-[normal] before:md:leading-[20.02px] before:md:list-outside before:md:list-disc before:md:absolute before:md:text-start before:md:indent-[0px] before:md:normal-case before:md:-translate-y-4 before:md:visible before:md:w-[calc(100%_+_8px)] before:md:z-[-1] before:md:border-separate before:md:-left-1 before:md:top-2/4 before:md:font-airbnb_cereal_vf after:md:accent-auto after:md:box-border after:md:text-neutral-800 after:md:block after:md:text-sm after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[20.02px] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-[calc(100%_+_70px)] after:md:z-[-1] after:md:rounded-[32px] after:md:border-separate after:md:top-0 after:md:font-airbnb_cereal_vf">
                  <div className="static box-content min-h-0 w-auto z-auto p-0 md:relative md:aspect-auto md:box-border md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-[2] md:overflow-clip md:[mask-position:0%] md:bg-left-top md:px-6 md:py-[15px] md:scroll-m-0 md:scroll-p-[auto]">
                    <div className="text-base font-normal box-content leading-[normal] text-clip text-wrap pb-0 md:text-xs md:font-medium md:aspect-auto md:box-border md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-clip md:[mask-position:0%] md:bg-left-top md:pb-0.5 md:scroll-m-0 md:scroll-p-[auto]">Check in</div>
                    <div className="box-content md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <div className="text-black box-content leading-[normal] text-clip text-wrap md:text-neutral-500 md:aspect-auto md:box-border md:leading-[18px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">Add dates</div>
                    </div>
                  </div>
                </div>
                <div className="bg-transparent box-content h-auto min-h-0 min-w-0 w-auto z-auto md:aspect-auto md:bg-zinc-300 md:box-border md:h-8 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-px md:z-[-2] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
                <div role="button" className="static [align-items:normal] box-content block h-auto justify-normal min-h-0 min-w-0 w-auto rounded-none md:relative md:items-center md:aspect-auto md:box-border md:flex md:h-full md:justify-between md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[32px] before:md:accent-auto before:md:box-border before:md:text-neutral-800 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-normal before:md:h-8 before:md:tracking-[normal] before:md:leading-[20.02px] before:md:list-outside before:md:list-disc before:md:absolute before:md:text-start before:md:indent-[0px] before:md:normal-case before:md:-translate-y-4 before:md:visible before:md:w-[calc(100%_+_8px)] before:md:z-[-1] before:md:border-separate before:md:-left-1 before:md:top-2/4 before:md:font-airbnb_cereal_vf after:md:accent-auto after:md:box-border after:md:text-neutral-800 after:md:block after:md:text-sm after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[20.02px] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-[calc(100%_+_70px)] after:md:z-[-1] after:md:rounded-[32px] after:md:border-separate after:md:top-0 after:md:font-airbnb_cereal_vf">
                  <div className="static box-content min-h-0 w-auto z-auto p-0 md:relative md:aspect-auto md:box-border md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-[2] md:overflow-clip md:[mask-position:0%] md:bg-left-top md:px-6 md:py-[15px] md:scroll-m-0 md:scroll-p-[auto]">
                    <div className="text-base font-normal box-content leading-[normal] text-clip text-wrap pb-0 md:text-xs md:font-medium md:aspect-auto md:box-border md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-clip md:[mask-position:0%] md:bg-left-top md:pb-0.5 md:scroll-m-0 md:scroll-p-[auto]">Check out</div>
                    <div className="box-content md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <div className="text-black box-content leading-[normal] text-clip text-wrap md:text-neutral-500 md:aspect-auto md:box-border md:leading-[18px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">Add dates</div>
                    </div>
                  </div>
                </div>
                <div className="bg-transparent box-content h-auto min-h-0 min-w-0 w-auto z-auto md:aspect-auto md:bg-zinc-300 md:box-border md:h-8 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-px md:z-[-2] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
                <div className="box-content min-h-0 min-w-0 md:aspect-auto md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <div role="button" className="static [align-items:normal] box-content block h-auto justify-normal w-auto rounded-none md:relative md:items-center md:aspect-auto md:box-border md:flex md:h-full md:justify-between md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[32px] before:md:accent-auto before:md:box-border before:md:text-neutral-800 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-normal before:md:h-8 before:md:tracking-[normal] before:md:leading-[20.02px] before:md:list-outside before:md:list-disc before:md:absolute before:md:text-start before:md:indent-[0px] before:md:normal-case before:md:-translate-y-4 before:md:visible before:md:w-[calc(100%_+_8px)] before:md:z-[-1] before:md:border-separate before:md:-left-1 before:md:top-2/4 before:md:font-airbnb_cereal_vf after:md:accent-auto after:md:box-border after:md:text-neutral-800 after:md:block after:md:text-sm after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[20.02px] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:z-[-1] after:md:rounded-[32px] after:md:border-separate after:md:top-0 after:md:font-airbnb_cereal_vf">
                    <div className="static box-content min-h-0 w-auto z-auto p-0 md:relative md:aspect-auto md:box-border md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-[2] md:overflow-clip md:[mask-position:0%] md:bg-left-top md:pl-6 md:pr-[130.904px] md:py-[15px] md:scroll-m-0 md:scroll-p-[auto]">
                      <div className="text-base font-normal box-content leading-[normal] text-clip text-wrap pb-0 md:text-xs md:font-medium md:aspect-auto md:box-border md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-clip md:[mask-position:0%] md:bg-left-top md:pb-0.5 md:scroll-m-0 md:scroll-p-[auto]">Who</div>
                      <div className="box-content md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <div className="text-black box-content leading-[normal] text-clip text-wrap md:text-neutral-500 md:aspect-auto md:box-border md:leading-[18px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">Add guests</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="static box-content z-auto right-auto md:absolute md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[2] md:[mask-position:0%] md:bg-left-top md:p-2.5 md:scroll-m-0 md:scroll-p-[auto] md:right-0"></div>
            </div>
          </div>
        </div>
        <div className="static bg-none box-content h-auto transform-none origin-[50%_50%] w-auto left-auto top-auto md:absolute md:aspect-auto md:bg-[linear-gradient(rgb(255,255,255)_39.9%,rgb(248,248,248)_100%)] md:box-border md:h-20 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:origin-[50%_0%] md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:scale-y-[2.5px] md:left-0 md:top-0 after:md:accent-auto after:md:bg-gray-200 after:md:box-border after:md:text-neutral-800 after:md:block after:md:text-sm after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-px after:md:tracking-[normal] after:md:leading-[20.02px] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:origin-[50%_0%] after:md:visible after:md:w-full after:md:border-separate after:md:scale-y-[0.4px] after:md:left-0 after:md:-bottom-px after:md:font-airbnb_cereal_vf"></div>
      </form>
      
      <div className="static bg-transparent box-content h-auto opacity-100 w-auto z-auto left-auto top-auto md:fixed md:aspect-auto md:bg-black/30 md:box-border md:h-[1000px] md:opacity-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-screen md:z-[-2] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-0"></div>
      <nav aria-label="Profile" className="static [align-items:normal] box-content block h-auto justify-normal min-h-0 min-w-0 md:relative md:items-center md:aspect-auto md:box-border md:flex md:h-20 md:justify-end md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="[align-items:normal] box-content gap-x-[normal] block grow-0 justify-normal min-h-0 min-w-0 gap-y-[normal] mr-0 md:items-center md:aspect-auto md:box-border md:gap-x-3 md:flex md:grow md:justify-end md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mr-3 md:scroll-m-0 md:scroll-p-[auto]">
          <button type="button" className="static font-normal bg-zinc-100 inline-block leading-[normal] min-h-0 min-w-0 text-center text-wrap px-1.5 py-px rounded-none md:relative md:font-medium md:aspect-auto md:bg-transparent md:block md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:px-3 md:py-[11px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[20px]">
            <span className="box-content inline text-wrap md:aspect-auto md:box-border md:inline-block md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">Become a host</span>
          </button>
          <div className="static box-content min-h-0 min-w-0 align-baseline my-0 md:relative md:aspect-auto md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:[mask-position:0%] md:bg-left-top md:my-auto md:scroll-m-0 md:scroll-p-[auto]">
            <button aria-label="Choose a language and currency" type="button" className="static [align-items:normal] bg-zinc-100 inline-block h-auto justify-normal leading-[normal] text-center w-auto rounded-none md:relative md:appearance-none md:items-center md:aspect-auto md:bg-zinc-100 md:inline-flex md:h-10 md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-10 md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%] before:md:accent-auto before:md:bg-zinc-100 before:md:box-border before:md:text-neutral-800 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-normal before:md:h-10 before:md:tracking-[normal] before:md:leading-[normal] before:md:list-outside before:md:list-disc before:md:absolute before:md:text-center before:md:indent-[0px] before:md:normal-case before:md:-translate-x-5 before:md:-translate-y-5 before:md:visible before:md:w-10 before:md:rounded-[50%] before:md:border-separate before:md:left-2/4 before:md:top-2/4 before:md:font-airbnb_cereal_vf">
              <span className="static [align-items:normal] box-content inline h-auto justify-normal min-h-0 min-w-0 w-auto md:relative md:items-center md:aspect-auto md:box-border md:flex md:h-10 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-10 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <img src="https://c.animaapp.com/me7emf7wZc0xCu/assets/icon-4.svg" alt="Icon" className="box-content h-auto align-middle w-auto md:aspect-auto md:box-border md:h-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-4 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
              </span>
            </button>
          </div>
        </div>
        <div className="box-content min-h-0 min-w-0 md:aspect-auto md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static box-content block md:relative md:aspect-auto md:box-border md:inline md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <button aria-label="Main navigation menu" type="button" className="static [align-items:normal] bg-zinc-100 inline-block h-auto justify-normal leading-[normal] text-center w-auto rounded-none md:relative md:appearance-none md:items-center md:aspect-auto md:bg-zinc-100 md:inline-flex md:h-10 md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-10 md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%] before:md:accent-auto before:md:bg-zinc-100 before:md:box-border before:md:text-neutral-800 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-normal before:md:h-10 before:md:tracking-[normal] before:md:leading-[normal] before:md:list-outside before:md:list-disc before:md:absolute before:md:text-center before:md:indent-[0px] before:md:normal-case before:md:-translate-x-5 before:md:-translate-y-5 before:md:visible before:md:w-10 before:md:rounded-[50%] before:md:border-separate before:md:left-2/4 before:md:top-2/4 before:md:font-airbnb_cereal_vf">
              <span className="static [align-items:normal] box-content inline h-auto justify-normal min-h-0 min-w-0 w-auto md:relative md:items-center md:aspect-auto md:box-border md:flex md:h-10 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-10 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <img src="https://c.animaapp.com/me7emf7wZc0xCu/assets/icon-5.svg" alt="Icon" className="box-content h-auto align-middle w-auto md:aspect-auto md:box-border md:h-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-4 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
              </span>
            </button>
          </div>
        </div>
      </nav>
    </header>
  );
}
