import React, { useState } from 'react';
import { PropertyData } from '../data/properties';

interface PropertyCardProps {
  property: PropertyData;
}

export function PropertyCard({ property }: PropertyCardProps) {
  const [isWishlisted, setIsWishlisted] = useState(false);

  const handleWishlistClick = () => {
    setIsWishlisted(!isWishlisted);
  };

  return (
    <div className={property.hasGuestFavorite ? "box-content min-h-0 min-w-0 z-auto md:aspect-auto md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-start md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" : "box-content min-h-0 min-w-0 md:aspect-auto md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-start md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"}>
      <div role="group" className="static box-content w-auto rounded-none md:relative md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[20px]">
        <a href={property.href} className="static box-content inline h-auto w-auto rounded-none left-auto top-auto md:absolute md:aspect-auto md:box-border md:block md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[20px] md:left-0 md:top-0"></a>
        <div className="box-content gap-x-[normal] block basis-auto flex-row grow-0 shrink gap-y-[normal] md:aspect-auto md:box-border md:gap-x-2 md:flex md:basis-full md:flex-col md:grow md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static bg-transparent box-content min-h-0 min-w-0 z-auto rounded-none md:relative md:aspect-auto md:bg-zinc-300 md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-0 md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[20px]">
            <div className="box-content md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <div className="box-content md:aspect-[20_/_19] md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="box-content h-auto md:aspect-auto md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <div role="presentation" className="static bg-repeat box-content basis-auto grow-0 h-auto w-auto md:relative md:aspect-auto md:bg-no-repeat md:box-border md:basis-[0%] md:grow md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-center md:scroll-m-0 md:scroll-p-[auto]">
                    <div className="[align-items:normal] box-content block h-auto justify-normal w-auto md:items-center md:aspect-auto md:box-border md:flex md:h-full md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <picture className="md:aspect-auto md:box-border md:block md:h-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <img alt="" src={property.image} className="box-content block h-auto object-fill align-middle w-auto md:aspect-auto md:box-border md:inline md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-bottom md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                      </picture>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="static box-content block [grid-template-areas:none] grid-cols-none grid-rows-none pt-0 px-0 inset-auto md:absolute md:aspect-auto md:box-border md:grid md:[grid-template-areas:'top-row_top-row_top-row''middle-row_middle-row_middle-row''bottom-row_bottom-row_bottom-row'] md:grid-cols-[repeat(3,minmax(0px,1fr))] md:grid-rows-[repeat(3,minmax(0px,1fr))] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:pt-3 md:px-3 md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
              <div className="box-content gap-x-[normal] block col-end-auto col-start-auto row-end-auto row-start-auto grid-cols-none min-h-0 min-w-0 md:aspect-auto md:box-border md:gap-x-2 md:grid md:col-end-[top-row] md:col-start-[top-row] md:row-end-[top-row] md:row-start-[top-row] md:grid-cols-[repeat(2,minmax(min-content,auto))] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                {property.hasGuestFavorite && (
                  <div className="box-content justify-self-auto min-h-0 min-w-0 md:aspect-auto md:box-border md:justify-self-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <div className="font-normal [align-items:normal] bg-transparent shadow-none box-content block h-auto max-w-none p-0 rounded-none md:font-semibold md:items-center md:aspect-auto md:backdrop-blur-[32px] md:bg-white/80 md:shadow-[rgba(0,0,0,0.02)_0px_0px_0px_1px,rgba(0,0,0,0.04)_0px_2px_6px_0px,rgba(0,0,0,0.1)_0px_4px_8px_0px] md:box-border md:inline-flex md:h-fit md:max-w-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:border md:[mask-position:0%] md:bg-left-top md:px-[9.5px] md:py-[5.5px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[14px] md:border-solid md:border-white/50">
                      <span className="static box-content inline h-auto text-wrap w-auto md:absolute md:aspect-auto md:box-border md:block md:h-px md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-px md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">Guest favorite</span>
                      <div className="text-base [align-items:normal] box-content block flex-nowrap leading-[normal] min-h-0 min-w-0 text-clip md:text-[11px] md:items-center md:aspect-auto md:box-border md:flow-root md:flex-wrap md:leading-[13px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <span className="box-content break-normal md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">Guest favorite</span>
                      </div>
                    </div>
                  </div>
                )}
                <div className="box-content block justify-self-auto min-h-0 min-w-0 md:aspect-auto md:box-border md:flex md:justify-self-end md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <div className="[align-items:normal] box-content block h-auto justify-normal min-h-0 min-w-0 w-auto mr-0 mt-0 md:items-center md:aspect-auto md:box-border md:flex md:h-8 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-8 md:[mask-position:0%] md:bg-left-top md:-mr-1 md:-mt-1 md:scroll-m-0 md:scroll-p-[auto]">
                    <button 
                      aria-label={`Add to wishlist: ${property.title}`} 
                      type="button" 
                      className="text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 inline-block h-auto justify-normal leading-[normal] min-h-0 min-w-0 text-center w-auto mt-0 px-1.5 py-px rounded-none md:text-base md:font-medium md:items-center md:aspect-auto md:bg-transparent md:flex md:h-8 md:justify-center md:leading-5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-8 md:[mask-position:0%] md:bg-left-top md:-mt-0.5 md:pt-0.5 md:pb-0 md:px-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"
                      onClick={handleWishlistClick}
                    >
                      <span className="box-content inline min-h-0 min-w-0 md:aspect-auto md:box-border md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <img src="https://c.animaapp.com/me7emf7wZc0xCu/assets/icon-8.svg" alt="Icon" className="box-content h-auto align-middle w-auto md:aspect-auto md:box-border md:h-6 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                      </span>
                    </button>
                  </div>
                </div>
              </div>
              <div className="[align-items:normal] box-content gap-x-[normal] block col-end-auto col-start-auto row-end-auto row-start-auto grid-cols-none min-h-0 min-w-0 mb-0 md:items-center md:aspect-auto md:box-border md:gap-x-3 md:grid md:col-end-[middle-row] md:col-start-[middle-row] md:row-end-[middle-row] md:row-start-[middle-row] md:grid-cols-[repeat(2,minmax(min-content,auto))] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mb-3 md:scroll-m-0 md:scroll-p-[auto]">
                <div className="box-content justify-self-auto min-h-0 min-w-0 md:aspect-auto md:box-border md:justify-self-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
                <div className="box-content justify-self-auto min-h-0 min-w-0 md:aspect-auto md:box-border md:justify-self-end md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
              </div>
              <div className="[align-items:normal] box-content gap-x-[normal] block col-end-auto col-start-auto row-end-auto row-start-auto grid-cols-none min-h-0 min-w-0 md:items-end md:aspect-auto md:box-border md:gap-x-2 md:grid md:col-end-[bottom-row] md:col-start-[bottom-row] md:row-end-[bottom-row] md:row-start-[bottom-row] md:grid-cols-[repeat(3,minmax(min-content,1fr))] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="box-content justify-self-auto min-h-0 min-w-0 md:aspect-auto md:box-border md:justify-self-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
                <div className="box-content justify-self-auto min-h-0 min-w-0 md:aspect-auto md:box-border md:justify-self-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
                <div className="box-content justify-self-auto min-h-0 min-w-0 md:aspect-auto md:box-border md:justify-self-end md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
              </div>
            </div>
          </div>
          <div className="box-content gap-x-[normal] block grid-cols-none min-h-0 min-w-0 gap-y-[normal] mx-0 md:aspect-auto md:box-border md:gap-x-0.5 md:grid md:grid-cols-[minmax(0px,1fr)] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-0.5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto]">
            <span className="text-base box-content inline leading-[normal] min-h-0 min-w-0 md:text-[13px] md:aspect-auto md:box-border md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <div className="font-normal box-content block text-clip md:font-medium md:aspect-auto md:box-border md:flow-root md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">{property.title}</div>
            </span>
            <div className="text-black text-base box-content block flex-nowrap leading-[normal] min-h-0 min-w-0 md:text-neutral-500 md:text-xs md:aspect-auto md:box-border md:flex md:flex-wrap md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <div className="box-content min-h-0 min-w-0 md:aspect-auto md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="box-content md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <div className="[align-items:normal] box-content block flex-nowrap md:items-baseline md:aspect-auto md:box-border md:flex md:flex-wrap md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <span className="static [align-items:normal] box-content inline min-h-0 min-w-0 md:relative md:items-baseline md:aspect-auto md:box-border md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <div className="box-content min-h-0 min-w-0 md:aspect-auto md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <div className="[align-items:normal] box-content block flex-nowrap justify-normal md:items-baseline md:aspect-auto md:box-border md:flex md:flex-wrap md:justify-start md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          <span className="box-content inline min-h-0 min-w-0 md:aspect-auto md:box-border md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">${property.price}</span>
                        </div>
                        <span className="static box-content inline h-auto text-wrap w-auto top-auto md:absolute md:aspect-auto md:box-border md:block md:h-px md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-px md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:top-0">${property.price} for 2 nights</span>
                      </div>
                      <div className="[align-items:normal] box-content block min-h-0 min-w-0 md:items-center md:aspect-auto md:box-border md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <span className="box-content inline min-h-0 min-w-0 md:aspect-auto md:box-border md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">for 2 nights</span>
                      </div>
                    </span>
                  </div>
                </div>
              </div>
              <span className="text-black font-normal box-content inline min-h-0 min-w-0 md:text-stone-300 md:font-bold md:aspect-auto md:box-border md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <span className="static box-content inline h-auto text-wrap w-auto md:absolute md:aspect-auto md:box-border md:block md:h-px md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-px md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">, </span>
                <span className="box-content md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"> · </span>
              </span>
              <span className="[align-items:normal] box-content gap-x-[normal] inline min-h-0 min-w-0 my-0 md:items-baseline md:aspect-auto md:box-border md:gap-x-[2.5px] md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:my-auto md:scroll-m-0 md:scroll-p-[auto]">
                <span className="static box-content inline h-auto text-wrap w-auto md:absolute md:aspect-auto md:box-border md:block md:h-px md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-px md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">{property.rating} out of 5 average rating</span>
                <span className="box-content inline min-h-0 min-w-0 my-0 md:aspect-auto md:box-border md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:my-auto md:scroll-m-0 md:scroll-p-[auto]">
                  <img src="https://c.animaapp.com/me7emf7wZc0xCu/assets/icon-9.svg" alt="Icon" className="box-content h-auto align-middle w-auto md:aspect-auto md:box-border md:h-2 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-2 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                </span>
                <span className="box-content inline min-h-0 min-w-0 md:aspect-auto md:box-border md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">{property.rating}</span>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
