import React from 'react';
import { PropertyCard } from './PropertyCard';
import { PropertyCarouselData } from '../data/properties';

interface PropertyCarouselProps {
  carousel: PropertyCarouselData;
}

export function PropertyCarousel({ carousel }: PropertyCarouselProps) {
  return (
    <div className="box-content md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] before:md:accent-auto before:md:box-border before:md:text-neutral-800 before:md:flex before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-normal before:md:tracking-[normal] before:md:leading-[20.02px] before:md:list-outside before:md:list-disc before:md:text-start before:md:indent-[0px] before:md:normal-case before:md:visible before:md:border-separate before:md:font-airbnb_cereal_vf after:md:accent-auto after:md:box-border after:md:text-neutral-800 after:md:flex after:md:text-sm after:md:not-italic after:md:normal-nums after:md:font-normal after:md:tracking-[normal] after:md:leading-[20.02px] after:md:list-outside after:md:list-disc after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:border-separate after:md:font-airbnb_cereal_vf">
      <div className="box-content block md:aspect-auto md:box-border md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div role="group" className="box-content block [grid-template-areas:none] grid-cols-none grid-rows-none md:aspect-auto md:box-border md:grid md:[grid-template-areas:'header''scroller''footer'] md:grid-cols-[minmax(0px,1fr)] md:grid-rows-[auto_auto_auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="box-content col-end-auto col-start-auto row-end-auto row-start-auto min-h-0 min-w-0 md:aspect-auto md:box-border md:col-end-[header] md:col-start-[header] md:row-end-[header] md:row-start-[header] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <div aria-label={carousel.ariaLabel} className="[align-items:normal] box-content block justify-normal m-0 md:items-center md:aspect-auto md:box-border md:flex md:justify-between md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-8 md:mb-3.5 md:mx-8 md:scroll-m-0 md:scroll-p-[auto]">
              <h2 className="box-content min-h-0 min-w-0 md:aspect-auto md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <a href={carousel.href} className="static box-content inline h-auto w-auto rounded-none md:relative md:aspect-auto md:box-border md:block md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg">
                  <span className="text-base font-normal [align-items:normal] box-content inline tracking-[normal] leading-[normal] pr-0 md:text-xl md:font-semibold md:items-baseline md:aspect-auto md:box-border md:inline-block md:tracking-[-0.18px] md:leading-6 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-3 md:scroll-m-0 md:scroll-p-[auto]">
                    {carousel.title}
                    <span className="box-content inline ml-0 md:aspect-auto md:box-border md:inline-block md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:ml-0.5 md:scroll-m-0 md:scroll-p-[auto]">
                      <img src="https://c.animaapp.com/me7emf7wZc0xCu/assets/icon-6.svg" alt="Icon" className="box-content h-auto align-middle w-auto md:aspect-auto md:box-border md:h-3 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-3 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                    </span>
                  </span>
                </a>
              </h2>
              <div className="[align-items:normal] box-content block min-h-0 min-w-0 ml-0 md:items-center md:aspect-auto md:box-border md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:ml-auto md:scroll-m-0 md:scroll-p-[auto]">
                <div className="box-content gap-x-[normal] block min-h-0 min-w-0 md:aspect-auto md:box-border md:gap-x-1 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <button aria-label="Previous" type="button" className="static text-black [align-items:normal] bg-zinc-100 inline-block h-auto justify-normal leading-[normal] min-h-0 min-w-0 opacity-100 text-center w-auto rounded-none md:relative md:appearance-none md:text-stone-300 md:items-center md:aspect-auto md:bg-white md:flex md:h-6 md:justify-center md:min-h-[auto] md:min-w-[auto] md:opacity-50 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6 md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%] before:md:accent-auto before:md:box-border before:md:text-stone-300 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-normal before:md:h-6 before:md:tracking-[normal] before:md:leading-[normal] before:md:list-outside before:md:list-disc before:md:absolute before:md:text-center before:md:indent-[0px] before:md:normal-case before:md:-translate-x-3 before:md:-translate-y-3 before:md:visible before:md:w-6 before:md:border before:md:border-stone-300 before:md:rounded-[50%] before:md:border-separate before:md:border-solid before:md:left-2/4 before:md:top-2/4 before:md:font-airbnb_cereal_vf">
                    <span className="static [align-items:normal] box-content inline justify-normal min-h-0 min-w-0 md:relative md:items-center md:aspect-auto md:box-border md:flex md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></span>
                  </button>
                  <button aria-label="Next" type="button" className="static [align-items:normal] bg-zinc-100 inline-block h-auto justify-normal leading-[normal] min-h-0 min-w-0 text-center w-auto rounded-none md:relative md:appearance-none md:items-center md:aspect-auto md:bg-zinc-100 md:flex md:h-6 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6 md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%] before:md:accent-auto before:md:bg-zinc-100 before:md:box-border before:md:text-neutral-800 before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-normal before:md:h-6 before:md:tracking-[normal] before:md:leading-[normal] before:md:list-outside before:md:list-disc before:md:absolute before:md:text-center before:md:indent-[0px] before:md:normal-case before:md:-translate-x-3 before:md:-translate-y-3 before:md:visible before:md:w-6 before:md:rounded-[50%] before:md:border-separate before:md:left-2/4 before:md:top-2/4 before:md:font-airbnb_cereal_vf">
                    <span className="static [align-items:normal] box-content inline justify-normal min-h-0 min-w-0 md:relative md:items-center md:aspect-auto md:box-border md:flex md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <span className="static box-content inline h-auto text-wrap w-auto md:absolute md:aspect-auto md:box-border md:block md:h-px md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-px md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">_</span>
                      <img src="https://c.animaapp.com/me7emf7wZc0xCu/assets/icon-7.svg" alt="Icon" className="box-content h-auto align-middle w-auto md:aspect-auto md:box-border md:h-3 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-3 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                    </span>
                  </button>
                </div>
              </div>
            </div>
            <div className="box-content md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
          </div>
          <div className="box-content col-end-auto col-start-auto row-end-auto row-start-auto justify-self-auto min-h-0 min-w-0 md:aspect-auto md:box-border md:col-end-[header] md:col-start-[header] md:row-end-[header] md:row-start-[header] md:justify-self-end md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
          <div className="box-content col-end-auto col-start-auto row-end-auto row-start-auto min-h-0 min-w-0 my-0 px-0 md:aspect-auto md:box-border md:col-end-[scroller] md:col-start-[scroller] md:row-end-[scroller] md:row-start-[scroller] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:-mt-1 md:-mb-2 md:px-8 md:scroll-m-0 md:scroll-p-[auto]">
            <div className="box-content md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <div className="box-content md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="box-content h-auto md:aspect-auto md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <div className="box-content gap-x-[normal] block auto-cols-auto grid-flow-row justify-normal overflow-x-visible overflow-y-visible gap-y-[normal] py-0 md:aspect-auto md:box-border md:gap-x-[11px] md:grid md:auto-cols-[calc(16.6667%_-_9.16667px)] md:grid-flow-col md:justify-start md:overflow-x-auto md:overflow-y-hidden md:overscroll-x-contain md:overscroll-y-auto md:gap-y-[11px] md:snap-align-none md:snap-normal md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pt-1 md:pb-2 md:scroll-m-0 md:scroll-px-0 md:scroll-py-[auto]">
                    {carousel.properties.map((property) => (
                      <PropertyCard key={property.id} property={property} />
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
